# Generated by Django 5.1.2 on 2024-10-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
