# Generated by Django 5.1.2 on 2024-10-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_topic_room_created_room_host_room_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='client',
            new_name='user',
        ),
    ]
