# Generated by Django 5.1.2 on 2025-01-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
