# Generated by Django 5.1.2 on 2025-01-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_room_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='phone',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
