# Generated by Django 5.1.2 on 2025-01-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_payment_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
