# Generated by Django 5.1.2 on 2025-02-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_update_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.room'),
        ),
    ]
