# Generated by Django 5.1.2 on 2025-03-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_update_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash_expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
