# Generated by Django 5.1.2 on 2025-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_cash_expenditure_alter_update_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash_expenditure',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='cash_expenditure',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cash_expenditure',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
