# Generated by Django 5.1.2 on 2025-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_cash_expenditure_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='month',
        ),
        migrations.AddField(
            model_name='update',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='Month',
            field=models.CharField(choices=[('JAN', 'MAY'), ('FEB', 'JUNE'), ('MAR', 'JULY'), ('APR', 'AUG'), ('MAY', 'SEP'), ('JUNE', 'OCT'), ('JULY', 'NOV'), ('AUG', 'august'), ('SEP', 'DEC'), ('OCT', 'DEC'), ('NOV', 'DEC'), ('DEC', 'DEC')], default='JAN', max_length=100),
        ),
    ]
