# Generated by Django 5.1.2 on 2025-04-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_update_month_update_name_update_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='Month',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='name',
            new_name='month',
        ),
    ]
