# Generated by Django 5.1.2 on 2025-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_room_child_room_parent_room_spouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='choice',
            field=models.CharField(choices=[('KANGOYA', 'Kangoya'), ('KASPHAT', 'Kasphat'), ('NGARA', 'Ngara'), ('GRACE_FAMILY', 'Grace_family'), ('WHITE_HOUSE', 'White_house'), ('KASARANI', 'Kasarani'), ('KIKUYU', 'Kikuyu'), ('KENYATTA', 'Kenyatta'), ('MUCATHA', 'Mucatha'), ('TRUTH_SEEKING', 'Truth_seekers'), ('RUIRU', 'Ruiru'), ('GACHIE', 'Gachie'), ('SHAMMAH', 'Shammah'), ('THINDIGUA', 'Thindigua'), ('MOMBASA_RD', 'Mombasa_rd'), ('JAMHURU', 'Jamhuri'), ('KAHAWA', 'Kahawa'), ('BLOOM_HILL_KAWAIDA', 'Bloom_hill_kawaida')], default='KANGOYA', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='HBC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
