# Generated by Django 5.1.2 on 2025-04-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_room_choice_alter_room_hbc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
