# Generated by Django 5.1.2 on 2025-04-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_room_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
