# Generated by Django 5.1.2 on 2025-04-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_update_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
