# Generated by Django 5.1.2 on 2025-06-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_room_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='choice',
            field=models.CharField(choices=[('KANGOYA', 'Kangoya'), ('KASPHAT', 'Kasphat'), ('NGARA', 'Ngara'), ('GRACE_FAMILY', 'Grace_family'), ('WHITE_HOUSE', 'White_house'), ('KASARANI', 'Kasarani'), ('KIKUYU', 'Kikuyu'), ('KENYATTA', 'Kenyatta'), ('MUCATHA', 'Mucatha'), ('TRUTH_SEEKERS', 'Truth_seekers'), ('RUIRU', 'Ruiru'), ('GACHIE', 'Gachie'), ('SHAMMAH', 'Shammah'), ('THINDIGUA', 'Thindigua'), ('MOMBASA_RD', 'Mombasa_rd'), ('JAMHURU', 'Jamhuri'), ('KAHAWA', 'Kahawa'), ('BLOOM_HILL_KAWAIDA', 'Bloom_hill_kawaida'), ('THIKA', 'Thika')], default='KANGOYA', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='identity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
