# Generated by Django 5.1.2 on 2025-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_alter_message_options_alter_update_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='choice',
            field=models.CharField(choices=[('ALL', 'ALL'), ('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='JANUARY', max_length=100),
        ),
    ]
