# Generated by Django 5.1.2 on 2025-06-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_update_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='choice',
            field=models.CharField(choices=[('Select', 'select'), ('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='Select', max_length=100),
        ),
    ]
