# Generated by Django 5.1.2 on 2025-06-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_msg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AlterModelOptions(
            name='msg',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
