# Generated by Django 5.1.2 on 2025-06-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_alter_message_options_alter_msg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
