# Generated by Django 5.1.2 on 2025-06-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='body',
            new_name='body2',
        ),
    ]
