# Generated by Django 5.1.2 on 2025-06-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_rename_body_msg_body2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='body2',
            new_name='body',
        ),
    ]
