# Generated by Django 5.1.2 on 2025-06-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_rename_body2_msg_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='body',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
