# Generated by Django 5.1.2 on 2025-07-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_msg_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msg',
        ),
    ]
