# Generated by Django 5.1.2 on 2025-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_delete_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='choice',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', max_length=100),
        ),
    ]
