# Generated by Django 5.1.2 on 2025-07-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_alter_update_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
