# Generated by Django 5.1.2 on 2025-07-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='update',
        ),
    ]
