# Generated by Django 5.1.2 on 2025-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_alter_update_choice_message_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='amount',
            new_name='Total_deductions',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Child',
        ),
        migrations.RemoveField(
            model_name='room',
            name='HBC',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Parent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Spouse',
        ),
        migrations.RemoveField(
            model_name='room',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='update',
            name='code',
        ),
        migrations.RemoveField(
            model_name='update',
            name='name',
        ),
        migrations.AddField(
            model_name='update',
            name='bbf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='current_loan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='deductable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='instalment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='kitty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='total_loan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='welfare_ded',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
