# Generated by Django 5.1.2 on 2025-08-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_rename_amount_update_total_deductions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cash_expenditure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cash_expenditure'),
        ),
    ]
