# Generated by Django 5.1.2 on 2025-08-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_room_cash_expenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_expenditure',
            name='Amount',
            field=models.CharField(max_length=45),
        ),
    ]
