# Generated by Django 5.1.2 on 2025-08-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_cash_expenditure_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amount',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
