# Generated by Django 5.1.2 on 2025-08-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_room_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash_expenditure',
            name='hosts',
        ),
    ]
